### PR TITLE
pc: sanitize ICE servers

### PR DESCRIPTION
**Pull request by saghul**
- Make sure the `urls` property is used, while supporting the deprecated `url`.
- Make sure all servers are lower-case since the C++ layer does a case insensitive parse.

Fixes: https://github.com/react-native-webrtc/react-native-webrtc/issues/1476

### CODE REVIEW

**Review by 8BallBomBom — APPROVED** [review]
Looks good to me, testing without hitches in general terms 👍🏻 
Seems to be sanitising as advertised.

Only hitch i'm getting are due to providing wonky ice server connection info but that is expected behavior.
There is a complete halt though if providing wonky params on peer creation but that can be ignored or addressed in another pr 😸 no biggie.

Then again maybe we could go down a more verbose route for everything when any incorrect params are used, future improvement?

**Comment by saghul** [comment]
What kind of wonky input makes it go boom?

**Comment by 8BallBomBom** [comment]
Not related to the `iceServers` but related to the initialization of peers in general.
You can cause the entire initialization to halt just as simple as that.
No errors or anything.

```javascript
let peer = new RTCPeerConnection( [] );
```

But then we are talking if doing things wrong 😨
Maybe we could look at sanitising and building in some extra type checks on everything?
As said, future improvement, might help some people along the way 😸

**Comment by 8BallBomBom** [comment]
> That's a weird one. That should fail the type check...

Exactly my thought 🤔

**Comment by PrakashkumarM** [comment]
Hi guys.
I'm experiencing the same issue even after applying the latest fix: "react-native-webrtc": "github:react-native-webrtc/react-native-webrtc#pull/1477/head". Interestingly, the problem only occurs when connected to the debugger. I appreciate any suggestions or solutions you might have.

**Comment by saghul** [comment]
What object are you passing to the PC constructor? Are you using the Chrome debugger?

**Comment by PrakashkumarM** [comment]
This is my peer connection setup.
const ICE_SERVERS = [
  {
    urls: "turn:turn.call.test.com:3500",
    username: "user",
    credential: "password",
  },
  // Add more ICE servers as needed
];

  // PeerConnection setup
  const peerConnection = useRef(
    new RTCPeerConnection({
      sdpSemantics: "unified-plan",
      offerToReceiveVideo: true,
      offerToReceiveAudio: true,
      iceServers: ICE_SERVERS,
    })
  );
  
  Yes I'm using chrome debugger

**Comment by saghul** [comment]
> sdpSemantics: "unified-plan",

This is not necessary.



> offerToReceiveVideo: true,
> offerToReceiveAudio: true,

This is not used by the PC constraints, it's something you may pass to createLocalDescription.



> Yes I'm using chrome debugger

That will not work because we use some sync methods. You need to disable it or the code won't work at all, which I suspect is the reson for your problem here.

**Comment by PrakashkumarM** [comment]
Kindly suggest an alternative debugger. I'm currently using React Native Debugger.

**Comment by saghul** [comment]
Flipper, or judiciously placed console.log statements 😅

**Pull request merged**
