### PR TITLE
Multiple video frame processors (+ implementation for ios)

### PR DESCRIPTION
**Pull request by wjaykim**
This PR adds support for registering multiple video frame processors.
Plus, it adds missing video frame processor functionality for ios platform as well.

### CODE REVIEW

**Comment by saghul** [comment]
Thank you! I'll provide a full review as soon as possible.

Quick question: what is your use case, that needs multiple processors at once?

**Comment by saghul** [comment]
Makes sense!

**Comment by 8BallBomBom** [comment]
@wjaykim When you get a chance could you rebase/resolve the conflicts on this please.
Then we can look at merging 👍🏻

**Comment by fukemy** [comment]
hi @wjaykim  can u provide sample processor like virtual background, blur... thanks so much

**Comment by wjaykim** [comment]
Sorry for late response. I pushed the conflicts resolved code.

**Comment by 8BallBomBom** [comment]
Will need a review and testing but possibly good to go for the next release 🤔
Should bring Android and iOS up to feature parity for the frame processor/effect handling.

**Comment by 8BallBomBom** [comment]
Hoping to test iOS soon but Android support seems to be working as expected.
@saghul Think we can include this with the next release or alongside M118?

**Comment by saghul** [comment]
I'd like to wait until 118 is done.

**Comment by 8BallBomBom** [comment]
No worries, gives extra time to test 😸

**Comment by 8BallBomBom** [comment]
Sorry for the late response.
We may include examples in the future.
As for this PR, i'll be looking to push it up soon.

**Comment by 8BallBomBom** [comment]
This is now slated to be worked on and included after the new-arch update 🤔
Mainly part of an effort to bring platform functionality closer together.
Seems better to split things up for a sound review process.

**Comment by saghul** [comment]
No worries and thanks for helping out! 🙏

**Pull request merged**
