### PR TITLE
fix(typescript): fix type for rtc view

### LINKED ISSUE #1218: Prop type errors on RTCView when using in TypeScript
#### Expected Behavior
Using the various props on RTCView (style, streamURL, objectFit, etc.) should work without type errors in TypeScript.

#### Observed Behavior
An error is raised when running `tsc`:

```
App.tsx:50:11 - error TS2322: Type '{ style: { flex: number; }; streamURL: string; objectFit: any; }' is not assignable to type 'IntrinsicAttributes & IntrinsicClassAttributes<Component<unknown, {}, any> & Readonly<NativeMethods>> & Readonly<...>'.
  Property 'style' does not exist on type 'IntrinsicAttributes & IntrinsicClassAttributes<Component<unknown, {}, any> & Readonly<NativeMethods>> & Readonly<...>'.

50           style={{ flex: 1 }}
             ~~~~~
```

#### Steps to reproduce the issue
Simply use RTCView in a typescript file and pass any props to it like so:

```
      <RTCView
          style={styles.videoView}
          streamURL={''}
          objectFit={'cover'}
        />
```

#### Platform Information

```
    "react": "18.1.0",
    "react-native": "0.70.5",
    "react-native-webrtc": "^106.0.0-beta.6"

    "typescript": "^4.8.3"
```

### PR DESCRIPTION
**Pull request by Kubessandra**
fixes #1218

### CODE REVIEW

**Review by saghul — APPROVED** [review]

**Comment by saghul** [comment]
Can you please fix the lint errors?

While you are at it, please move the comments to be close to the matching props.

**Review by saghul — CHANGES_REQUESTED** [review]
The linter fails.

**Comment by Kubessandra** [comment]
> The linter fails + comments

Done

**Comment by saghul** [comment]
Thank you!

**Pull request merged**
