### PR TITLE
M56

### PR DESCRIPTION
**Pull request by zxcpoiu**
ios/android: upgrade webrtc to branch 56 stable 15101 (+12 16107)

This is based on previous M55 with **rebased** latest master changes.

## MAJOR CHANGES:

* about M55, see #184 
* (android/ios) can supports custom constraints passed in `create offer/answer` by it's `options` param
* (android only) can supports rest of custom configuration options passed into `PeerConnectionInit`, include some hidden options.
* (android only) use sourceId to select video device is NOT necessary but optional, you can just pass `facingMode` and it will select for you.

## NOTE:

* ios VP9 codec included #175
* ios now compiled with arm/arm64 (#141 #183), so iPad and Simulator are not supported.

## TODO

* ios: implements the rest of configuration options like android
* android: should normalize video resolution params, now in `java` side, we still use `minWidth` ...etc, should be normalized according to spec ( the `exact` key word ? )

## Later TODO

* M57 is releasing
* consider cherry picks ios submission bug described in #223 which fixed till M58
* refactor DEMO Project

### CODE REVIEW

**Comment by saghul** [comment]
Damm. I have a M57 PR almost ready. I'll see where we can meet in the middle.

**Comment by zxcpoiu** [comment]
@saghul 

does your PR includes android as well?
or you can point me where your branch is and I can try to merge into this PR as a follow up

hmm...next time we should open an issue and create a branch for upgrade PR to compare

**Comment by saghul** [comment]
@zxcpoiu Yep, Android too. I can make builds with the 4 architectures for both Android and iOS. I'll base my PR on yours, I think that's the safest bet now.

I'm in the process of testing Android, once I got it working I'll PR my changes.

On hindsight I should have opened an issue, but I thought the update process was kinda stalled, so I didn't bother. My bad!

**Comment by zxcpoiu** [comment]
@saghul 

awesome!
I am going to implement the rest of peer connection configurations till then :+1: 
modify my code/coding convention/naming directly if anything you think better

I didn't open an issue as well , what I mean is, I can open an issue/empty PR indicating working process to avoid duplicate efforts and provide a one commit point branch :smile: 

so the architecture would be:

* android: armv7/x86
* ios: arm/arm64 with vp9 codec

right?

**Comment by saghul** [comment]
> so the architecture would be:
> 
> android: armv7/x86
> ios: arm/arm64 with vp9 codec
> right?

Iv'e got armv7, arm64, x86 and x64 builds for both :-) I'm recompiling now with VP9 support enabled.

**Comment by saghul** [comment]
@zxcpoiu I merged your PR onto M56 and I'm now going to PR M57 after some fixes which were required.

**Pull request merged**
