### PR TITLE
Modern constraints

### PR DESCRIPTION
**Pull request by saghul**
This PR implements modern style constraints and the ability to customize the resolution and framerate. All feedback is welcome!

### CODE REVIEW

**Comment by iZaL** [comment]
waiting for this PR to get merged

**Comment by iZaL** [comment]
@danjenkins yes, I will do that and get back. thanks

**Comment by vakrolme** [comment]
Does this mean that config.js is now working on mobile Jitsi Meet client?

**Comment by saghul** [comment]
@vakrolme Can you reprase? config.js was always working, if you mean if the config values get taken into consideration, then yes, that should be the case now. Note that the `constraints` value is not yet used, but resolution`. We are working on this at the moment.

**Comment by vakrolme** [comment]
@saghul yes, I'm confused about the process of setting custom constraints for mobile Jitsi. 

In short, I want to prioritize resolution over fps, so that resolution always stays as high as possible while fps may drop to as low as 13. There's an [older topic](https://community.jitsi.org/t/jitsi-dev-how-to-change-resolution-and-frame-rate-fps-of-jitsi/13883/15?u=froschgesicht) about constraints on Jitsi community forum, but it seems outdated because of this pull request.

So the question is where can I set `min` and `ideal` for both resolution & fps, and how?

P.S. somewhat off-topic: is there a way to set the RtpEncodingParameter `degradationPreference` to `maintain-resolution`?

**Comment by saghul** [comment]
> So the question is where can I set `min` and `ideal` for both resolution & fps, and how?

In the `constraints` directive. Note, as I said earlier, that we don't use that yet, it's going to happen very very soon.

> P.S. somewhat off-topic: is there a way to set the RtpEncodingParameter `degradationPreference` to `maintain-resolution`?

Not at the moment. We'd have to implement support for that in this plugin to begin with.

**Comment by vakrolme** [comment]
Thanks for a swift reply!

> it's going to happen very very soon.

Is there an estimate on the release?

**Comment by saghul** [comment]
> Is there an estimate on the release timeframe?

I'm working on it this week. It may slip to the next.

**Comment by vakrolme** [comment]
> > Is there an estimate on the release timeframe?
> 
> I'm working on it this week. It may slip to the next.

@saghul can you please give some update, whether the issue was de-prioritized?

**Comment by saghul** [comment]
Yep it got pushed back due to unforeseen issues that need fixing beforehand, sorry about that.

**Comment by vakrolme** [comment]
> Yep it got pushed back due to unforeseen issues that need fixing beforehand, sorry about that.

Are these issues also responsible for `maxFps` being ignored on mobile? https://github.com/jitsi/jitsi-meet/issues/4946

I've just found out about `maxFps` and `minFps` and tried using them as a substitute for constraints, but they don't seem to be taken into consideration.

My `config.js`:
```
    resolution: 1080,
    minFps: 13,
    maxFps: 25,
```

**Comment by saghul** [comment]
No, all of those are ignored.

**Pull request merged**
