### PR TITLE
fixed addObject exception on ios17

### PR DESCRIPTION
**Pull request by mtdxc**

### CODE REVIEW

**Comment by saghul** [comment]
What exception do you get?

**Comment by mtdxc** [comment]
Incompatible pointer types initializing 'NSMutableArray *' with an expression of type 'NSArray *'
it will got exception on new xcode.

**Comment by saghul** [comment]
What xcode version did you use?

**Comment by davidliu** [comment]
@mtdxc Can you rebase from master and repush? Just merged a commit to master that fixes the ios CI compile error you have.

**Comment by saghul** [comment]
@davidliu Are you observing this bug? I am not, when compiling with Xcode 15.2. Not opposing the change though.

**Comment by davidliu** [comment]
> @davidliu Are you observing this bug? I am not, when compiling with Xcode 15.2. Not opposing the change though.

Yeah, hits the exception on my iOS 17.5.1 device, compiled with Xcode 15.4.

**Pull request merged**
