### PR TITLE
Android RN 72 Support - Update build.gradle w/ Namespace

### PR DESCRIPTION
**Pull request by 1nspir3d**
RN Team Update:
https://github.com/react-native-community/discussions-and-proposals/issues/671

Fix:
https://github.com/react-native-community/discussions-and-proposals/issues/671#issuecomment-1598892444

### CODE REVIEW

**Comment by 8BallBomBom** [comment]
Been following for a while.
Thanks for the contribution 👍🏻 

I'll push this forward for the next release.

**Comment by saghul** [comment]
@8BallBomBom Quick note going forward when merging PRs: please use squash-merge and edit the commit message so the release notes looks better, thanks!

**Comment by 8BallBomBom** [comment]
@saghul Will do, no worries 😸

**Comment by saghul** [comment]
Cheers!

**Comment by 8BallBomBom** [comment]
Actually wasn't aware that made such a difference to the auto changelog generator 🤔 
No problem though, I've fixed it 👍🏻 should be better than it was 😅

**Pull request merged**
