### PR TITLE
docs-etc, random stuff

### PR DESCRIPTION
**Pull request by 8BallBomBom**
Will be starting on this soon.
As always i'm open to suggestions 😃 

- [x] Kill off the old examples, will be linked to the new repo soon
- [ ] Migrate documentation over to the new repo

### CODE REVIEW

**Comment by 8BallBomBom** [comment]
@saghul I'll work on this pr and the new repo, then we can push ahead over time 👍🏻

**Comment by saghul** [comment]
I invited you to the org, let me know when you accept so I can add you to the examples repo and you can start the work there.

Regarding documentation, and since you seem to also want to reference other projects, how about we create a docs repo with a Docusaurus setup? I've had success using it for the Jitsi handbook: https://jitsi.github.io/handbook/ Since it's just markdown files it's easy to maintain and contribute to.

**Comment by 8BallBomBom** [comment]
That sounds perfect 😄 then we can just move everything, link from here to there 👍🏻

**Comment by 8BallBomBom** [comment]
Just checked over [here](https://github.com/jitsi/handbook).
Looks pretty interesting, well all in all i could do documentation which covers the modules in the org and also any of the random use cases which might include outside modules 👍🏻

**Comment by saghul** [comment]
Yeah, we can go step by step. I'll try to get the docs repo setup.

**Comment by saghul** [comment]
> Yeah, we can go step by step. I'll try to get the docs repo setup.

Ah wait you can do it yourself too now :-) I saw you created a handbook repo. Great start. Let me know if you want me to kickstart the docusausurs project, I do have some experience with it. If you want to dive it, make sure you use v2.

**Comment by 8BallBomBom** [comment]
That would greatly help, not sure if i've got access to the examples repo 😅 
Also unsure what permissions to set on the other repo but set you as an admin nevertheless 👍🏻

**Comment by saghul** [comment]
Ah I see. Added you to the examples repo too!

**Comment by 8BallBomBom** [comment]
Thanks for that, will start committing soon.
If you could get a kickstart done on the handbook then i'd appreciate it and start filling things in from there 👍🏻 

Just been looking over Docusaurus and i must say as it uses React, already off to a good start 😄 
Should be pretty decent.

**Comment by 8BallBomBom** [comment]
Currently changing net providers so it will be a few days before getting started.
Looking forward to filling in as much as possible though 🚀

**Comment by 8BallBomBom** [comment]
Needs some consideration, unsure about adjustments on the readme to link over to the handbook.

**Comment by saghul** [comment]
Shall we revisit this after the first unified plan stable release?

**Comment by 8BallBomBom** [comment]
Been working on some much needed changes to bring things up to spec but that sounds reasonable 😃
But i'm also unsure if i should just dump in the new code samples or do a migration guide.
Also still have an example project to finish but haven't moved along with that fully yet as i was investigating module changes needed for the new RN architecture 😮

**Comment by saghul** [comment]
> Been working on some much needed changes to bring things up to spec but that sounds reasonable 😃
> 
> Unsure if i should just dump in the new code samples or do a migration guide.
> 

Honestly, there is plenty of material out there about WebRTC. I don't see this plugin as a place where core concepts need to be taught, but where WebRTC is applied to a specific platform, namely react native.

So that said, I think what is important is for us to document how / where we diverge from the web environment.

> 
> 
> Also still have an example project to finish but haven't moved along with that fully yet as i was investigating module changes needed for the new RN architecture 😮

Thanks for doing that!

**Comment by 8BallBomBom** [comment]
No worries, will switch out some stuff for the major update and then we can have examples for the key parts.
Will update this branch and link things over once the unified plan stable release goes out 👍🏻

**Comment by 8BallBomBom** [comment]
Gonna close this and start on a new PR after the stable release goes out 👍🏻

**Comment by saghul** [comment]
👍

**Pull request closed without merging**
