### PR TITLE
Change event handlers over to getters/setters

### PR DESCRIPTION
**Pull request by 8BallBomBom**
Will need some testing as this was thrown together 👍🏻 
Might be a good idea moving things up to the  constructor 🤔

### CODE REVIEW

**Comment by saghul** [comment]
The docs suggest stronger type annotations which I see you had and then removed. What happened there?

**Comment by 8BallBomBom** [comment]
I can add them back but pretty much a whole bunch of errors about the amount of arguments not being acceptable 🤔

**Comment by saghul** [comment]
I see. If this fixes it, let's go with it and improve it later if necessary.

**Comment by 8BallBomBom** [comment]
No worries, will run some tests and ensure the events are firing as expected but as for the error others have been experiencing, that is a bit of a pickle, not managed to reproduce 🤔

**Comment by saghul** [comment]
Since it looks like this might not be necessary after all, shall we close it and revisit if / when needed?

**Comment by 8BallBomBom** [comment]
Best bet, close it, revisit if and when needed due to package rot/updates over time 😅

**Comment by saghul** [comment]
> Maybe once the deprecated code has actually been removed?

Unlikely to happen anytime soon, so sure :-)

**Comment by 8BallBomBom** [comment]
Never really liked getters/setters anyway 🤣 all that extra code seems kinda dirty.

**Pull request closed without merging**
