### PR TITLE
Try and force the use of the correct event-target-shim module.

### PR DESCRIPTION
**Pull request by 8BallBomBom**
Quick pr, untested but will test shortly 👍🏻 

Hopefully Fixes https://github.com/react-native-webrtc/react-native-webrtc/issues/1503

### CODE REVIEW

**Review by saghul — APPROVED** [review]
LGTM, if it works :-)

**Comment by 8BallBomBom** [comment]
Sorry for the wait.
The coast is clear by the looks of things 😅 
After a couple of tests with a non Expo and Expo app, everything appears to be working as intended.

**Comment by saghul** [comment]
Excellent! Please go ahead and merge this then.

**Comment by b0iq** [comment]
@davidliu Hi, Could you please merge this in [livekit/react-native-webrtc](https://github.com/livekit/react-native-webrtc) ?

**Pull request merged**
