### PR TITLE
Add video frame layout (size and rotation) event

### PR DESCRIPTION
**Pull request by anion155**
I needed the way to get video size from RTCView. I made this fork.

### CODE REVIEW

**Comment by saghul** [comment]
Thanks for the PR! Code looks good. I'm a bit on the fence about it because it's non-standard, but the same can be said about mirroring I guess... Also IIRC this information is missing from new stats.

**Comment by anion155** [comment]
Standart has `MediaStreamTrack#getSettings` method for this kind of information. https://developer.mozilla.org/en-US/docs/Web/API/MediaTrackSettings https://w3c.github.io/mediacapture-main/#dom-mediastreamtrack-getsettings

**Comment by saghul** [comment]
True that. I guess we could emit an event and capture the values internally so they can be returned when getSettings is called on the track.

**Comment by sesm** [comment]
@anion155 sorry, if I'm missing something, but you can get video width and height from `getStats()` in `googFrameHeightReceived` and `googFrameWidthReceived`

**Comment by anion155** [comment]
@sesm https://developer.mozilla.org/en-US/docs/Web/API/RTCStatsReport

**Comment by saghul** [comment]
@sesm That's what I suggested, yeah. But if I'm not mistaken those are gone in the new stats (that we are not yet using)

**Comment by anion155** [comment]
> @sesm https://developer.mozilla.org/en-US/docs/Web/API/RTCStatsReport

I mean, that there is no such stats in standart.

**Comment by saghul** [comment]
See page 14 here: https://docs.google.com/document/d/1z-D4SngG36WPiMuRvWeTMN7mWQXrf1XKZwVl3Nf1BIE It's alreeady part of the new stats. You should be able to use the legacy one right now, since it's what this plugin uses, still.

**Pull request closed without merging**
