### PR TITLE
Virtual Background functionality with Selfie Segmentator framework

### PR DESCRIPTION
**Pull request by bipmeet**

### CODE REVIEW

**Review by saghul — COMMENTED** [review]
Thanks for sharing!

**Comment by Desintegrator** [comment]
@bipmeet could you please provide a simple project example with this functionality? I've try to implement this, but build fails with some errors (such as SelfieSegmentator file not found)
Thank you in advance

**Comment by fukemy** [comment]
hi, any android solution?

**Comment by fukemy** [comment]
@saghul plz accept this

**Comment by fukemy** [comment]
hi @bipmeet , did u  tent to support install your force through npm? It's help us too much

**Comment by saghul** [comment]
Please stop it.

We are not going to add this as is. A GSoC student is adding support for injecting these types of filters from the outside, Android is mostly ready, check the open PRs.

**Comment by fukemy** [comment]
thanks @saghul, I am finding virtual background for Android too, but I can not find any PR related to Android, can u help?

**Comment by saghul** [comment]
Literally the last one.

**Comment by fukemy** [comment]
look good, I found it? Thanks so much, sorry for silly question, I am not know much about PR github <3

**Review by fukemy — CHANGES_REQUESTED** [review]
i got this error: ***<SelfieSegmentatorGpu/SelfieSegmentator.h>*** not found. Can u tested again?

**Comment by Desintegrator** [comment]
@fukemy same. As i reported above, im not able to run and check it

**Comment by fukemy** [comment]
> @fukemy same. As i reported above, im not able to run and check it

Hi, did u found any solution. I tried 2 days, searching many problem in stackoverflow but can not solved this

**Comment by Desintegrator** [comment]
> > @fukemy same. As i reported above, im not able to run and check it
> 
> Hi, did u found any solution. I tried 2 days, searching many problem in stackoverflow but can not solved this

unfortunately not ((

useless PR

**Comment by saghul** [comment]
No need to be disrespectful. At least they did something, unlike you who is just complaining.

**Comment by Desintegrator** [comment]
You never know what im doing

**Pull request closed without merging**
