### PR TITLE
api: RTCDataChannel buffer amount implementation

### PR DESCRIPTION
**Pull request by 8BallBomBom**
Should be up to scratch but needs testing 👍🏻 
Follows on from [#1082](https://github.com/react-native-webrtc/react-native-webrtc/pull/1082)

**Edit:**
Needs a kick after #1246 #1249

### CODE REVIEW

**Comment by 8BallBomBom** [comment]
Unsure if we should consider adding an event to reflect how much data has buffered instead of just having `bufferedamountlow` as the changed amount is being given over from native.

@saghul Thoughts?

**Comment by saghul** [comment]
IIRC there is no standard API for that, is there?

**Comment by 8BallBomBom** [comment]
Not that i'm aware, pretty much why i left it out 😨

**Comment by saghul** [comment]
Merged, can you pl rebase this one?

**Comment by 8BallBomBom** [comment]
Will do 👍🏻

**Comment by 8BallBomBom** [comment]
Bare with me, gonna re-open with the changes again.

**Comment by 8BallBomBom** [comment]
Should be good to go but needs testing 👍🏻

**Comment by 8BallBomBom** [comment]
All good to go 👍🏻

**Comment by 8BallBomBom** [comment]
Alrighty, now we're all good to go 😆

**Review by saghul — APPROVED** [review]

**Comment by saghul** [comment]
Thanks for pushing this over the finish line!

**Comment by 8BallBomBom** [comment]
Glad to help 👍🏻

**Pull request merged**
