### PR TITLE
add sending of dtmf ability

### PR DESCRIPTION
**Pull request by danjenkins**
Enable us sending DTMF

### CODE REVIEW

**Comment by saghul** [comment]
Hi Dan! Sorry it took me a bit to review this. AFAICT the implemented API does not follow any spec, ie it's custom. That's not something this project aims to do, except when there is no "standard" way to do it.

Now, given the current state of our APIs (stream based, now considered deprecated) I think the best course of action is to implement it as RTCPeerConnection.createDTMFSender(). See: https://developer.mozilla.org/en-US/docs/Web/API/WebRTC_API/Using_DTMF Here is how I implemented it for Cordova back in the day: https://github.com/BasqueVoIPMafia/cordova-plugin-iosrtc/commit/427d80e28b62a60235507bf727c574e3b7be6cc0

**Comment by redexp** [comment]
@saghul `createDTMFSender()` is deprecated. Instead of it `getSenders()` should be used like this

```javascript
let sender = pc.getSenders()[0];
sender.dtmf.insertDTMF("1", 500, 50);
```
[getSenders()](https://developer.mozilla.org/en-US/docs/Web/API/RTCPeerConnection/getSenders), [RTCRtpSender](https://developer.mozilla.org/en-US/docs/Web/API/RTCRtpSender), [RTCDTMFSender](https://developer.mozilla.org/en-US/docs/Web/API/RTCDTMFSender), [insertDTMF()](https://developer.mozilla.org/en-US/docs/Web/API/RTCDTMFSender/insertDTMF)

**Comment by saghul** [comment]
I know. But we don't have `getSenders` yet, so that was a suggestion for a stopgap.

**Comment by redexp** [comment]
@saghul As I understand all of this api are ready on android and ios side, all we need is to proxy them to js side, right? I can try to do that.

**Comment by saghul** [comment]
iOS is also ready on the native side IIRC. The devil is always on the details ;-) Feel free to open a PR, that would be much appreciated!

**Comment by harishgupta01** [comment]
Hi, Are you guys planning to this pull request?  

https://github.com/react-native-webrtc/react-native-webrtc/pull/642/commits/d5bf74d0379c48446987cd1bd90653f774f5b83b

**Comment by saghul** [comment]
Not in the current shape.

**Comment by sebamarucci** [comment]
Hi all,
I updated react-native-webrtc lib to implemented these two functions for iOS and Android:
`sendDtmfTone(dtmfTone, duration, interToneGap)`
`canInsertDtmf()`

I tried on a personal project and they seem to be working.

@saghul should I update current PR or create a new one?

**Comment by saghul** [comment]
Closing. Now that we have unified plan this would need to be implemented following the w3c API.

**Pull request closed without merging**
