### PR TITLE
ios,android: setCodecPreferences and getCapabilities

### PR DESCRIPTION
**Pull request by davidliu**
Related upstream patches:

ios: https://webrtc-review.googlesource.com/c/src/+/305200

android: https://webrtc-review.googlesource.com/c/src/+/304880

Not sure when the objc will land and when we can upgrade to it, but posting this PR in advance.

### CODE REVIEW

**Comment by saghul** [comment]
This is looking really good. I reckon we can cherry pick the upstream patches once iOS lands and release 114 or 115.

**Comment by saghul** [comment]
FYI I pulled your patch into the JitsiWebRTC build and put this patch in the M118 PR: https://github.com/react-native-webrtc/react-native-webrtc/pull/1462

**Comment by 8BallBomBom** [comment]
Seems the Android patch was merged upstream but the iOS patch was reversed over [here](https://webrtc-review.googlesource.com/c/src/+/322000?tab=comments).
Was going to close this as things have been merged with the M118 pr.
But leaving open as the iOS patches are unresolved 🤔

**Comment by saghul** [comment]
I merged the patch in JitsiWebRTC, I'm tired of waiting for months for such a trivial change.

**Comment by 8BallBomBom** [comment]
Understandable but as they reverted the iOS patch due to something breaking, thought maybe something we might need to investigate even with things being upstreamed in JitsiWebRTC 🤔 

Otherwise we can close this?

**Comment by saghul** [comment]
We can close this because I integrated it in the M118 PR. I'm following up upstream (we have a reland CL) because that breakage is nonesense.

**Comment by 8BallBomBom** [comment]
Alrighty, just had to be sure 😸

**Pull request closed without merging**
