### PR TITLE
added videoFrameProcessor which rotate the videoframe by multiple of 90 degree

### PR DESCRIPTION
**Pull request by SHIVAJIKUMAR007**
I have created a class by implementing VideoProcessor interface and get VideoFrame object in onFrameCaptured method

### CODE REVIEW

**Comment by SHIVAJIKUMAR007** [comment]
I have created registry for register video effect and discard video effect 

MediaStreamTrack._setVideoEffect(name)    for effect registry 
MediaStreamTrack._discardVideoEffect()     to discard the effect

**Comment by Desintegrator** [comment]
@SHIVAJIKUMAR007 Hi! What about iOS? Can we implement such a video processor there?

**Comment by SHIVAJIKUMAR007** [comment]
have a look on this 
https://github.com/bipmeet/react-native-webrtc-vb/commit/4e812951c357a6b767a587aebfa8694f6db0580a

**Comment by Desintegrator** [comment]
@SHIVAJIKUMAR007 cannot run even example project with this changes :(

**Comment by saghul** [comment]
Superseded by https://github.com/react-native-webrtc/react-native-webrtc/pull/1176

**Pull request closed without merging**
