### PR TITLE
Fix (Android): Fix variable naming

### PR DESCRIPTION
**Pull request by cpoile**
Fixes a var naming collision that was preventing the android build from completing.
Related to #1277 .

### CODE REVIEW

**Review by saghul — APPROVED** [review]
Sigh, thanks!

**Comment by 8BallBomBom** [comment]
My bad on that one, will try and test more 👍🏻

**Comment by cpoile** [comment]
@8BallBomBom No worries, I'm happy to contribute. :)

**Comment by 8BallBomBom** [comment]
Thanks but i was referring to the couple of releases that went out with android issues 😅
Not to worry though 👍🏻

**Comment by santhoshvai** [comment]
My bad actually! apologies for the broken code

**Comment by saghul** [comment]
We now have a CI that would have caught it!

**Pull request merged**
