### PR TITLE
android,ios: fix matching remote streams in onTrack

### PR DESCRIPTION
**Pull request by saghul**
Fixes: https://github.com/react-native-webrtc/react-native-webrtc/issues/1309

### CODE REVIEW

**Comment by Romick2005** [comment]
It doesn't help for my case. The issue exist when connection is made between Android -> Android ( no remote video for the caller, but both video local and remote works for the callee). For iOS->Android, Android->iOS, iOS->iOS it works fine.

With this fix both Android devices does not show remote video. In previous version only caller does not have remote video.

But at least now it is consistent ).

**Comment by saghul** [comment]
Do you see a new stream in ontrack, with a different react tag?

**Comment by streamer45** [comment]
Gave this a go and cannot reproduce the issue any longer. Incoming streams/tracks with previously seen ids are now played as expected.

**Comment by saghul** [comment]
> Gave this a go and cannot reproduce the issue any longer. Incoming streams/tracks with previously seen ids are now played as expected.

Thanks for confirming! @Romick2005 i suspect yours is a different issue.

**Pull request merged**
